// <auto-generated />
using System;
using Ditado.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ditado.Infra.Migrations
{
    [DbContext(typeof(DitadoDbContext))]
    [Migration("20251204055009_AdicionarAutorECategorias")]
    partial class AdicionarAutorECategorias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ditado.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.Ditado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("AudioLeitura")
                        .IsRequired()
                        .HasColumnType("MEDIUMBLOB");

                    b.Property<int?>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Ditados", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.DitadoCategoria", b =>
                {
                    b.Property<int>("DitadoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAssociacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DitadoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("DitadoCategorias", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.DitadoSegmento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DitadoId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DitadoId", "Ordem")
                        .IsUnique();

                    b.ToTable("DitadoSegmentos", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.RespostaDitado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DitadoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Pontuacao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("DitadoId");

                    b.ToTable("RespostaDitados", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.RespostaSegmento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Correto")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RespostaDitadoId")
                        .HasColumnType("int");

                    b.Property<string>("RespostaFornecida")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SegmentoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoErro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RespostaDitadoId");

                    b.HasIndex("SegmentoId");

                    b.ToTable("RespostaSegmentos", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProfessorResponsavelId")
                        .HasColumnType("int");

                    b.Property<string>("Semestre")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorResponsavelId");

                    b.ToTable("Turmas", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUltimoAcesso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("TurmaAluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "TurmaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("TurmaAluno");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.Ditado", b =>
                {
                    b.HasOne("Ditado.Dominio.Entidades.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.DitadoCategoria", b =>
                {
                    b.HasOne("Ditado.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("DitadoCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ditado.Dominio.Entidades.Ditado", "Ditado")
                        .WithMany("DitadoCategorias")
                        .HasForeignKey("DitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Ditado");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.DitadoSegmento", b =>
                {
                    b.HasOne("Ditado.Dominio.Entidades.Ditado", "Ditado")
                        .WithMany("Segmentos")
                        .HasForeignKey("DitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ditado");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.RespostaDitado", b =>
                {
                    b.HasOne("Ditado.Dominio.Entidades.Ditado", "Ditado")
                        .WithMany("Respostas")
                        .HasForeignKey("DitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ditado");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.RespostaSegmento", b =>
                {
                    b.HasOne("Ditado.Dominio.Entidades.RespostaDitado", "RespostaDitado")
                        .WithMany("RespostasSegmentos")
                        .HasForeignKey("RespostaDitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ditado.Dominio.Entidades.DitadoSegmento", "Segmento")
                        .WithMany("Respostas")
                        .HasForeignKey("SegmentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RespostaDitado");

                    b.Navigation("Segmento");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.Turma", b =>
                {
                    b.HasOne("Ditado.Dominio.Entidades.Usuario", "ProfessorResponsavel")
                        .WithMany("TurmasComoProfessor")
                        .HasForeignKey("ProfessorResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProfessorResponsavel");
                });

            modelBuilder.Entity("TurmaAluno", b =>
                {
                    b.HasOne("Ditado.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ditado.Dominio.Entidades.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("DitadoCategorias");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.Ditado", b =>
                {
                    b.Navigation("DitadoCategorias");

                    b.Navigation("Respostas");

                    b.Navigation("Segmentos");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.DitadoSegmento", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.RespostaDitado", b =>
                {
                    b.Navigation("RespostasSegmentos");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("TurmasComoProfessor");
                });
#pragma warning restore 612, 618
        }
    }
}
