// <auto-generated />
using System;
using Ditado.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ditado.Infra.Migrations
{
    [DbContext(typeof(DitadoDbContext))]
    partial class DitadoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ditado.Dominio.Entidades.Ditado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("AudioLeitura")
                        .IsRequired()
                        .HasColumnType("MEDIUMBLOB");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Ditados", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.DitadoSegmento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DitadoId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DitadoId", "Ordem")
                        .IsUnique();

                    b.ToTable("DitadoSegmentos", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.RespostaDitado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DitadoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Pontuacao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("DitadoId");

                    b.ToTable("RespostaDitados", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.RespostaSegmento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Correto")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RespostaDitadoId")
                        .HasColumnType("int");

                    b.Property<string>("RespostaFornecida")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SegmentoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoErro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RespostaDitadoId");

                    b.HasIndex("SegmentoId");

                    b.ToTable("RespostaSegmentos", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUltimoAcesso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.DitadoSegmento", b =>
                {
                    b.HasOne("Ditado.Dominio.Entidades.Ditado", "Ditado")
                        .WithMany("Segmentos")
                        .HasForeignKey("DitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ditado");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.RespostaDitado", b =>
                {
                    b.HasOne("Ditado.Dominio.Entidades.Ditado", "Ditado")
                        .WithMany("Respostas")
                        .HasForeignKey("DitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ditado");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.RespostaSegmento", b =>
                {
                    b.HasOne("Ditado.Dominio.Entidades.RespostaDitado", "RespostaDitado")
                        .WithMany("RespostasSegmentos")
                        .HasForeignKey("RespostaDitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ditado.Dominio.Entidades.DitadoSegmento", "Segmento")
                        .WithMany("Respostas")
                        .HasForeignKey("SegmentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RespostaDitado");

                    b.Navigation("Segmento");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.Ditado", b =>
                {
                    b.Navigation("Respostas");

                    b.Navigation("Segmentos");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.DitadoSegmento", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("Ditado.Dominio.Entidades.RespostaDitado", b =>
                {
                    b.Navigation("RespostasSegmentos");
                });
#pragma warning restore 612, 618
        }
    }
}
